//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzurePolicyEvaluatorTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BasicResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BasicResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzurePolicyEvaluatorTests.BasicResources", typeof(BasicResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;name&quot;: &quot;nsg-app&quot;,
        ///    &quot;type&quot;: &quot;Microsoft.Network/networkSecurityGroups&quot;,
        ///    &quot;location&quot;: &quot;northeurope&quot;,
        ///    &quot;properties&quot;: {
        ///        &quot;securityRules&quot;: [
        ///            {
        ///                &quot;type&quot;: &quot;Microsoft.Network/networkSecurityGroups/securityRules&quot;,
        ///                &quot;properties&quot;: {
        ///                    &quot;protocol&quot;: &quot;*&quot;,
        ///                    &quot;sourcePortRange&quot;: &quot;*&quot;,
        ///                    &quot;destinationPortRange&quot;: &quot;22&quot;,
        ///                    &quot;sourceAddressPrefix&quot;: &quot;*&quot;,
        ///                    &quot;destinationAdd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NSG_AllowSSH {
            get {
                return ResourceManager.GetString("NSG_AllowSSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Policy_Location_List {
            get {
                object obj = ResourceManager.GetObject("Policy_Location_List", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;name&quot;: &quot;8abf7f28-f631-4700-9ff7-26f7e994458a&quot;,
        ///    &quot;type&quot;: &quot;Microsoft.Authorization/policyDefinitions&quot;,
        ///    &quot;properties&quot;: {
        ///        &quot;displayName&quot;: &quot;deny-ports-nsg&quot;,
        ///        &quot;description&quot;: &quot;need to add description&quot;,
        ///        &quot;metadata&quot;: {
        ///            &quot;version&quot;: &quot;1.0.0&quot;,
        ///            &quot;category&quot;: &quot;Network&quot;
        ///        },
        ///        &quot;mode&quot;: &quot;All&quot;,
        ///        &quot;parameters&quot;: {
        ///            &quot;effect&quot;: {
        ///                &quot;type&quot;: &quot;String&quot;,
        ///                &quot;metadata&quot;: {
        ///                    &quot;displayName&quot;: &quot;Effec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Policy_NSG_DenyPorts {
            get {
                return ResourceManager.GetString("Policy_NSG_DenyPorts", resourceCulture);
            }
        }
    }
}
