name: ci

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "src/**"
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        runtime:
          - os: windows-latest
            rid: win-x64
          - os: ubuntu-latest
            rid: linux-x64
          - os: macos-latest
            rid: osx-x64

    runs-on: ${{ matrix.runtime.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish ${{ matrix.runtime.os }}
        working-directory: src/AzurePolicyEvaluator
        run: dotnet publish --runtime ${{ matrix.runtime.rid }} --output output

      - name: Release tests
        run: src/AzurePolicyEvaluator/output/ape -r samples

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v3
        if: matrix.runtime.os == 'ubuntu-latest'
        with:
          name: ape-linux
          path: src/AzurePolicyEvaluator/output/ape

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v3
        if: matrix.runtime.os == 'macos-latest'
        with:
          name: ape-macos
          path: src/AzurePolicyEvaluator/output/ape

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v3
        if: matrix.runtime.os == 'windows-latest'
        with:
          name: ape-windows
          path: src/AzurePolicyEvaluator/output/ape.exe
